### ISSUE TITLE
No "main" or "exports" field indefined in package.json

### ISSUE THREAD

**Issue by chrisspiegl** [Touffy/dl-stream#5]
Just got an error message with this package in my Nuxt/Vue application and think it could be fixed on this package to prevent unnecessary logging:

```
[2:51:59 PM]  ERROR  (node:45277) [DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json for /node_modules/dl-stream/ resolving the main entry point "index.js", imported from /node_modules.
Default "index" lookups for the main are deprecated for ES modules.
```

Basically, the build process complains that `dl-stream` has no `main` or `exports` field and is falling back to the `index.js`.

Adding the following to `package.json` should do the trick:

```json
"main": "index.js"
```

**Comment by Touffy** [comment]
Sure. I thought the `module` field was enough, but that didn't really catch on. The standard thing seems to be `exports` now (I don't know, I guess some older tools may expect `main` to point to a CommonJS module only).
You want to do the PR ?

**Comment by chrisspiegl** [comment]
At this time, I am not deep enough to know which of the two would be the correct one to add, as I have not developed any modules like this.

I just thought I'd report it so that others may not run into the same warning.

**Comment by Touffy** [comment]
Fixed and published.

**Comment by chrisspiegl** [comment]
I just pulled the update into my project and the warning is gone. Thank you, @Touffy.
