### ISSUE TITLE
Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by artyuum** [Touffy/dl-stream#6]
I'm trying to use this package in an Angular app and I'm encountering the following error:
> Module not found: Error: Default condition should be last one

After doing some research online, I found this solution: 
https://stackoverflow.com/a/76127619

I believe the issue comes from this commit (7f4e871). It seems like `types` should be placed before `default`:
https://github.com/Touffy/dl-stream/blob/7f4e871f594f4724fff30c77cc61e8c2241a4692/package.json#L6-L9

**Comment by Touffy** [comment]
Thank you. The [Node.js documentation](https://nodejs.org/api/packages.html#packages_conditional_exports) does say "default" *should always come last*.

**Comment by Touffy** [comment]
Just published.

**Comment by artyuum** [comment]
> Thank you. The [Node.js documentation](https://nodejs.org/api/packages.html#packages_conditional_exports) does say "default" _should always come last_.

Well that's odd. I just tried the new version you published and it works now :)

**Comment by Touffy** [comment]
Why is that odd ? I merged your change.

**Comment by artyuum** [comment]
The fact that Node.js documentation indicates that "default" should always be placed last, but doing so actually triggers an error.

**Comment by Touffy** [comment]
Your bundler complained when "default" was *not* last. Your PR moved it to the end of the list and now you say your bundler is happy. So it's consistent with the docs.

**Comment by artyuum** [comment]
Oh my bad, I misunderstood the docs. All good.
